# Generated by Django 5.1.6 on 2025-04-15 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Watch',
        ),
    ]
