# Generated by Django 5.1.6 on 2025-04-15 11:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_order_watch'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Watch',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='app.watch'),
            preserve_default=False,
        ),
    ]
