# Generated by Django 5.1.6 on 2025-04-17 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_order_watch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Watch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.watch'),
        ),
    ]
